### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by antun008** [MapsHD/HDMapping#25]
Can you give us dataset and guide for saving las, imu and gsss into usb ?

**Comment by antun008** [comment]
what exactly do i need to do to get las, imu and gnss files. Should I follow the instructions you wrote in Mandeye? Wiring manual, and other things? For me this is to difficult.

Can you explain this part better, please. Beacsue i downloaded this exe file from hdmapping, but dont know how to get datasets and I also having Livox mid 360 and working with fastlio

**Comment by JanuszBedkowski** [comment]
Please provide me Your email so I can send some data

**Comment by antun008** [comment]
Thanks a lot!:))
Email: antun006@gmail.com

and I forgot to write, superb work!

**Comment by CharlieV5** [comment]
> Please provide me Your email so I can send some data

Hi!  I would like to have some example data too ! Here is my e-mail: charliev5@qq.com
Thank you very much!
