### ISSUE TITLE
Holding System

### ISSUE THREAD

**Issue by BestVanRome** [MapsHD/HDMapping#29]
Hi James,

on your pictures you are having an attachement gripper, which seems to be generaly usable on the all the "platforms" / animals. 

Can you share, what you are using there? 

Thanx

**Comment by JanuszBedkowski** [comment]
It is Ronin-S BG37 Grip.

**Comment by BestVanRome** [comment]
But this is only the handle, you have something like a gripper that holds for example to the side on the boat. 
What did you use there?

**Comment by JanuszBedkowski** [comment]
Ulanzi
https://ulanzi.com.pl/uchwyty-i-mocowania/328-imadlo-zacisk-z-glowica-magic-arm-ulanzi-r094-6972436386581.html
https://ulanzi.com.pl/uchwyty-i-mocowania/202-podwojny-zacisk-imadlo-ulanzi-r096-6972436388004.html

**Comment by JanuszBedkowski** [comment]
issue solved
