### ISSUE TITLE
Problem with loading georeferenced scan

### ISSUE THREAD

**Issue by lredovnikovic** [MapsHD/HDMapping#32]
[LIDAR23b.zip](https://github.com/MapsHD/HDMapping/files/15407022/LIDAR23b.zip)
I am trying to load a georeferenced point cloud as described in the manual in chapter 5.1. After I save the .json file, instead of having an offset to the right coordinates, all the offsets are zero.
Do you know what caused the issue?

**Comment by JanuszBedkowski** [comment]
fixed in release v0.40
