### ISSUE TITLE
No executable program generated after compilation

### ISSUE THREAD

**Issue by CharlieV5** [MapsHD/HDMapping#33]
Hi! I tried to compile the code on Ubuntu 20.04 ROS noetic with catkin_make, but no executable program is generated in the "devel" folder. The same with the "[mandeye_to_bag](https://github.com/michalpelka/mandeye_to_bag)"

**Comment by JanuszBedkowski** [comment]
It is not ROS project.
Please do this 

git clone https://github.com/MapsHD/HDMapping.git
cd HDMapping
mkdir build
git submodule init
git submodule update --recursive
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j

programs will be in 'build' folder

**Comment by JanuszBedkowski** [comment]
"[mandeye_to_bag](https://github.com/michalpelka/mandeye_to_bag)" is ROS project 
please make issue there

**Comment by CharlieV5** [comment]
Thank you!
