### ISSUE TITLE
getting stuck in step 1

### ISSUE THREAD

**Issue by yuckinus** [MapsHD/HDMapping#37]
Hello

Was in balkan cavers camp and we tried the collected data on your machine which processed fine for steps 1 and 2. Got back home and trying to do the same but getting stuck in step 1, tried two times

![image](https://github.com/MapsHD/HDMapping/assets/40965122/d63e1f43-8a75-4ca4-a020-d71ae3599bcc)

**Comment by antun008** [comment]
If I'm right:
If the window in the program does not turn white when you click on it, it indicates that the program has created a process and you can proceed to the next step in step 1. Honestly, I don't know why it doesn't show in the last line of code that it has reached the end, but in reality, it seems to me that it practically goes through everything. Conclusion: just try to continue processing as if everything is fine.

**Comment by JanuszBedkowski** [comment]
I add 
std::cout << "step_1_done please click 'compute_all (step 2)' to continue calculations" << std::endl; 


<img width="858" alt="Zrzut ekranu 2024-06-03 230531" src="https://github.com/MapsHD/HDMapping/assets/1889422/b32754ac-491b-45c3-aa09-9ce618de2cc3">
