### ISSUE TITLE
Add error report for GCP

### ISSUE THREAD

**Issue by antun008** [MapsHD/HDMapping#49]
Please can you maybe put error after georefencing with GCP and split errors in X, Y and H coordinates. I think it would help the person understand whether the greater error is in the horizontal or vertical sense.

Best Regards,
Antun Jakopce.

**Comment by JanuszBedkowski** [comment]
done, example:

----------------------------
Ground control points report
--
GCP[0] name: 'gcp_7'
delta_x: 2.15087e-05 [m], delta_y: 0.00190449 [m], delta_z: -1.21924e-05 [m]
GCP-> x:27.33 [m], y:40.61 [m], z:-0.328 [m]
TrajectoryNode-> x:27.33 [m], y:40.61 [m], z:-0.328
--
--
GCP[1] name: 'gcp_6'
delta_x: 0.0345655 [m], delta_y: -0.0558896 [m], delta_z: 0.000267708 [m]
GCP-> x:-38.502 [m], y:63.617 [m], z:-0.308 [m]
TrajectoryNode-> x:-38.502 [m], y:63.617 [m], z:-0.308
--
--
GCP[2] name: 'gcp_14'
delta_x: -0.0345871 [m], delta_y: 0.0539678 [m], delta_z: -0.000255515 [m]
GCP-> x:0 [m], y:0 [m], z:0 [m]
TrajectoryNode-> x:0 [m], y:0 [m], z:0
--
