### ISSUE TITLE
Step 3 Manual pose...

### ISSUE THREAD

**Issue by DariuszWilczewski** [MapsHD/HDMapping#69]
edit: To jest mój pierwszy wpis, zatem Dzień dobry. 
Jestem użytkownikiem Mandeye od pół roku. (to ten co chciał koniecznie zrobić georefernecję)

Powinienem zapytać czy i w jakiej formie mogę zgłaszać propozycje zmian w programie?
Czy angielski jest obowiązkowy?
no i na koniec ale nie mniej ważne: Czy ktoś to będzie czytał? ;)

Uwaga nr 1:
W step 2 są powiększone numery odcinków do tworzenia edge, w step 3  również można by to było powiększyć.

Pozdrawiam Darek

**Comment by JanuszBedkowski** [comment]
Hi,
English is prefered since this project is dedicated for international audience. 

I addressed this issue in commit "solving issue #69"

**Comment by JanuszBedkowski** [comment]
It is proper way to comunicate errors, bugs, claims:)

**Comment by JanuszBedkowski** [comment]
THX

**Comment by DariuszWilczewski** [comment]
so I see that there are readers ;)
next posts in english, got it
