### ISSUE TITLE
Consistency vs Consistency2

### ISSUE THREAD

**Issue by bo-rc** [MapsHD/HDMapping#71]
Hi there are one `Consistency` and the other `Consistency2` buttons in the GUI app `lidar_odometry_step_1`. 

Are they providing the same effects? I notice that `Consistency2` is much slower. I'm wondering if there is a quality / speed trade-off between the two?

![Screenshot from 2024-10-08 21-05-19](https://github.com/user-attachments/assets/b910156b-5bb5-4c72-993b-7c51da5c61f5)

**Comment by antun008** [comment]
I think consistency2 is better for indoor

**Comment by JanuszBedkowski** [comment]
<img width="962" alt="Zrzut ekranu 2024-10-17 085801" src="https://github.com/user-attachments/assets/7ac6e417-f240-4263-ade3-c65da9ca66b3">

I updated GUI

**Comment by JanuszBedkowski** [comment]
I hope GUI explains everything
