### ISSUE TITLE
Reopening Processed Folders/Files

### ISSUE THREAD

**Issue by mhl787156** [MapsHD/HDMapping#74]
Hi, am at the workshop -

I wanted to reopen an already processed project, but the load_project seems to fail. 

```
input_file_names.size(): 14
laz_files.size(): 7
csv_files.size(): 35
condition: input_file_names.size() > 0 && laz_files.size() == csv_files.size() NOT SATISFIED!!!
```

Is there a way to reopen a previously processed file? 
Currently I have to delete the whole folder, re-copy it and retry.

**Comment by JanuszBedkowski** [comment]
Yes you can, just mark only *laz and *csv files.
