### ISSUE TITLE
Corrupted files?

### ISSUE THREAD

**Issue by DariuszWilczewski** [MapsHD/HDMapping#75]
Scan like any other, but I can't pass step_1 (v.0.60) (edit: same issue with 0.62)
I can't move even with this few starting filles.  Step_1 just shuts down and no comments left.
Is this dataset corrupted somehow? If so, then why? what did I do wrong during survey?

[TEST.zip](https://github.com/user-attachments/files/17704307/TEST.zip)

**Comment by JanuszBedkowski** [comment]
Please check v0.63 and follow instructions. If it is not sufficient please add new issue.

**Comment by DariuszWilczewski** [comment]
Solved, thx

"ł" in path,
