### ISSUE TITLE
Question regarding processing stopscan dataset

### ISSUE THREAD

**Issue by MattiasTancred** [MapsHD/HDMapping#77]
Hi, big thanks for all the work put into this repo and the accompanying controller repo.

I have tested processing a stopscan dataset for the first time.

It might be due to my limited knowledge, but I am doing something similar to continuous scanning. Then I load session.json in step 2 and get the following.
<img width="1213" alt="hdmapping" src="https://github.com/user-attachments/assets/ebd8a8cb-b88f-40f0-96fa-f2feef6cba1c">

**Comment by GeomPozzoli** [comment]
Hi Mattias,
I think scans done in stop scan mode should be managed like scans done with a static laser scanner, therefore individual laz files can be registered with other software such as cloudcompare (very complicated), I have never tried to manage them as if they were mobile, I will try to do some experiments
Stefano

**Comment by JanuszBedkowski** [comment]
Hi, step 2 multi_view_tls_registration_step_2.exe can do this 

<img width="1280" alt="Zrzut ekranu 2024-12-12 142541" src="https://github.com/user-attachments/assets/ebe12d27-3807-45c5-9280-239a0a20c99d" />


<img width="1280" alt="Zrzut ekranu 2024-12-12 142418" src="https://github.com/user-attachments/assets/1c41f767-a3c9-4bea-83f3-75ab4390defb" />





all methods are elaborated here 
https://www.sciencedirect.com/science/article/abs/pii/S0263224123007637


If You have an issue to use this function let me know

**Comment by JanuszBedkowski** [comment]
Please use gizmo to move scans

<img width="1280" alt="Zrzut ekranu 2024-12-12 143003" src="https://github.com/user-attachments/assets/60d9bc7d-79f8-4e35-a81e-33e6e532b6dd" />

**Comment by JanuszBedkowski** [comment]
use e.g. NDT for multi view registration

<img width="1280" alt="Zrzut ekranu 2024-12-12 143217" src="https://github.com/user-attachments/assets/cdc01e2c-da51-4066-9312-4b596eecdce5" />

**Comment by JanuszBedkowski** [comment]
I think I lost documentation for this :), not so many people were interested in this particular functionality.
Software supports ICP, NDT, point to point, point to plane, plane to plane, point to projection, different angle reprezentation such as Tait Bryan, quaternion, Rodrigues ...

**Comment by MattiasTancred** [comment]
@JanuszBedkowski - Thank you very much for your detailed response. I appreciate the time and effort you put into explaining the solution.

I realized that I had missed the section you mentioned.

![bild](https://github.com/user-attachments/assets/e1b08af3-da26-462a-9360-afa963fc7181)

 Everything is working as expected.

I plan to explore the various parts of these functions in more depth and will reach out if I encounter any difficulties along the way.

Once again, thank you for your incredible work and for contributing to the open-source community.

Regards

**Comment by JanuszBedkowski** [comment]
Ok
